import random #inbuild library for generating the random numbers

#Define the range and data type of the random number, ensuring it has only 2 decimal points
Random_Number = round((random.uniform(1.00, 1.50)),2)

#Title of the game
print("GUESS THE NUMBER CONTEST 2K25!!\nGuess the random number between 1.00 and 1.50") #Title

#Actual random number generated by the system for testing purposes
print(f"Actual system generated random number is:{Random_Number} (This line is for testing purpose. Please comment out this line in the code when the real game starts)")

#Conditions to compare the player's guess with the actual system generated random number within the corresponding range
Attempts = 0
while True:
    Guessed_Number = float(input("Enter your guess:"))
    Attempts += 1
    if Guessed_Number > Random_Number:
        print("Too high, you're close to the target. Please try again!")
    elif Guessed_Number < Random_Number:
        print("Too low, you're close to the target. Please try again!")
    else:
        print(f"Congratulations mate!\nYou found the number in {Attempts} attempt(s)")
        break
